# Generated by Django 5.0.7 on 2024-08-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0009_sponsor_sponsorship"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="sponsored_hackathons",
            field=models.ManyToManyField(
                related_name="sponsors", to="students.hackathon"
            ),
        ),
    ]
