# Generated by Django 5.0.7 on 2024-09-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0011_room_membershiprequest_roommembership_room_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="students.skill"
            ),
        ),
    ]
